services:
  data-store:
      build:
        context: ../funding-service-design-post-award-data-store
      command: bash -c "flask run -p 8080 -h 0.0.0.0"
      volumes: ['../funding-service-design-post-award-data-store:/app']
      ports:
        - 4001:8080
  frontend:
      build:
        context: ../funding-service-design-post-award-data-frontend
        dockerfile: Dockerfile
      volumes: ['../funding-service-design-post-award-data-frontend:/app']
      command: bash -c "flask run -p 8080 -h 0.0.0.0"
      depends_on:
        - data-store
      ports:
        - 4002:8080
        - 5688:5678
